"""transaksi bisa dibatalkan (buku append-only)

Revision ID: 12e4f362ee11
Revises: a8efcd8180ff
Create Date: 2026-07-20 06:28:30.375508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e4f362ee11'
down_revision: Union[str, None] = 'a8efcd8180ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dibatalkan_pada', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('koreksi_dari_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_dibatalkan_pada'), ['dibatalkan_pada'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_koreksi_dari_id'), ['koreksi_dari_id'], unique=False)
        # FK WAJIB dinamai: autogenerate menulis `None`, dan `drop_constraint(None)`
        # di downgrade akan gagal (pelajaran yang berulang di repo ini).
        batch_op.create_foreign_key(
            "fk_transactions_koreksi_dari", 'transactions', ['koreksi_dari_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_koreksi_dari", type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_koreksi_dari_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_dibatalkan_pada'))
        batch_op.drop_column('koreksi_dari_id')
        batch_op.drop_column('dibatalkan_pada')

    # ### end Alembic commands ###
