"""skema inti: 4 pilar + model biaya extensible

Revision ID: 3d659af26c6b
Revises: 
Create Date: 2026-07-18 02:40:55.451425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d659af26c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panduan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topik', sa.String(length=40), nullable=False),
    sa.Column('jenis_usaha', sa.String(length=120), nullable=True),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('sumber_url', sa.String(length=400), nullable=False),
    sa.Column('tanggal_akses', sa.Date(), nullable=False),
    sa.Column('berlaku_sampai', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panduan_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panduan_entries_topik'), ['topik'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('no_hp', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_hp')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_usaha', sa.String(length=160), nullable=False),
    sa.Column('jenis_usaha', sa.String(length=120), nullable=True),
    sa.Column('lokasi', sa.String(length=160), nullable=True),
    sa.Column('mulai_usaha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_user_id'), ['user_id'], unique=False)

    op.create_table('cost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('material', 'labor_time', 'overhead', name='tipe_komponen'), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('satuan_baku', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_items_business_id'), ['business_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.Enum('laporan', 'proposal_kur', name='jenis_dokumen'), nullable=False),
    sa.Column('periode', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_business_id'), ['business_id'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('sumber', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sebagian', 'selesai', 'batal', name='status_impor'), nullable=False),
    sa.Column('ringkasan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_business_id'), ['business_id'], unique=False)

    op.create_table('kur_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kur_interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kur_interviews_business_id'), ['business_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_business_id'), ['business_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('jenis', sa.Enum('reseller', 'produksi', name='jenis_produk'), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_business_id'), ['business_id'], unique=False)

    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('skor_total', sa.Integer(), nullable=True),
    sa.Column('komponen', sa.JSON(), nullable=True),
    sa.Column('periode', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_snapshots_business_id'), ['business_id'], unique=False)

    op.create_table('hpp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('hpp_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rincian', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hpp_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hpp_snapshots_product_id'), ['product_id'], unique=False)

    op.create_table('kur_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('hasil', sa.Enum('diajukan', 'lolos', 'ditolak', name='hasil_kur'), nullable=False),
    sa.Column('plafon_cair', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('alasan_penolakan', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kur_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kur_outcomes_business_id'), ['business_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('yield_satuan', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_product_id'), ['product_id'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.Enum('pemasukan', 'pengeluaran', 'operasional', 'prive', name='jenis_transaksi'), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.Column('kategori_detail', sa.String(length=80), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('sumber_input', sa.Enum('chat', 'impor', 'manual', name='sumber_input'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('cost_item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_cost_item_id'), ['cost_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tanggal'), ['tanggal'], unique=False)

    op.create_table('cost_item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_item_id', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('sumber', sa.Enum('transaksi', 'ditanya', name='sumber_harga'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_item_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_item_prices_cost_item_id'), ['cost_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_item_prices_tanggal'), ['tanggal'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('keyakinan', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'diterima', 'ditolak', name='status_baris_impor'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_import_id'), ['import_id'], unique=False)

    op.create_table('recipe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('cost_item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cost_item_id'], ['cost_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_items_cost_item_id'), ['cost_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_items_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_items_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_items_cost_item_id'))

    op.drop_table('recipe_items')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_import_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('cost_item_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_item_prices_tanggal'))
        batch_op.drop_index(batch_op.f('ix_cost_item_prices_cost_item_id'))

    op.drop_table('cost_item_prices')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tanggal'))
        batch_op.drop_index(batch_op.f('ix_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_cost_item_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_business_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_product_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('kur_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kur_outcomes_business_id'))

    op.drop_table('kur_outcomes')
    with op.batch_alter_table('hpp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hpp_snapshots_product_id'))

    op.drop_table('hpp_snapshots')
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_snapshots_business_id'))

    op.drop_table('score_snapshots')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_business_id'))

    op.drop_table('products')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_business_id'))

    op.drop_table('messages')
    with op.batch_alter_table('kur_interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kur_interviews_business_id'))

    op.drop_table('kur_interviews')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_business_id'))

    op.drop_table('imports')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_business_id'))

    op.drop_table('documents')
    with op.batch_alter_table('cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_items_business_id'))

    op.drop_table('cost_items')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_user_id'))

    op.drop_table('businesses')
    op.drop_table('users')
    with op.batch_alter_table('panduan_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panduan_entries_topik'))

    op.drop_table('panduan_entries')
    # ### end Alembic commands ###
