"""harga jual majemuk: product_prices

Revision ID: a8efcd8180ff
Revises: f680a7bfc3e3
Create Date: 2026-07-19 03:26:21.627459
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8efcd8180ff'
down_revision: Union[str, None] = 'f680a7bfc3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kanal', sa.String(length=40), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('harga', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('berlaku_dari', sa.Date(), nullable=False),
    sa.Column('catatan', sa.String(length=160), nullable=True),
    sa.CheckConstraint('harga >= 0', name='ck_product_prices_harga'),
    sa.CheckConstraint('min_qty IS NULL OR min_qty > 0', name='ck_product_prices_min_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_prices_berlaku_dari'), ['berlaku_dari'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_prices_product_id'), ['product_id'], unique=False)

    # ⚠️ Pindahkan dulu harga yang sudah ada, BARU buang kolomnya. Kebalikannya
    # membuang data pengguna tanpa jejak.
    #
    # `berlaku_dari` sengaja dipatok ke tanggal lampau, BUKAN `created_at`:
    # kolom skalar lama tidak bertanggal, artinya ia berlaku kapan saja. Memberi
    # tanggal mulai yang belakangan akan membuat laporan periode lampau
    # kehilangan harga jualnya — mengubah angka pengguna diam-diam.
    op.execute("""
        INSERT INTO product_prices (product_id, kanal, grade, min_qty, harga, berlaku_dari, catatan)
        SELECT id, NULL, NULL, NULL, harga_jual, '1970-01-01',
               'dipindah dari products.harga_jual (tak bertanggal)'
        FROM products
        WHERE harga_jual IS NOT NULL
    """)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('harga_jual')


def downgrade() -> None:
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_jual', sa.NUMERIC(precision=14, scale=2), nullable=True))

    # Kembalikan hanya harga umum terbaru. Harga per kanal/grade/tier tidak punya
    # padanan di kolom skalar dan memang hilang — itu konsekuensi turun versi,
    # bukan bug yang perlu disembunyikan.
    op.execute("""
        UPDATE products SET harga_jual = (
            SELECT harga FROM product_prices
            WHERE product_prices.product_id = products.id
              AND kanal IS NULL AND grade IS NULL AND min_qty IS NULL
            ORDER BY berlaku_dari DESC, id DESC LIMIT 1
        )
    """)

    with op.batch_alter_table('product_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_prices_berlaku_dari'))

    op.drop_table('product_prices')
